---
- name: Implementing when conditions
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present
        update_cache: no
      when: a == 20
