---
- name: Implementing play scope variables
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: Install s/w's
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...

